from selenium.webdriver.common.by import By


class Locators:
    MAIN_CAT_ALL_OFFERS = (By.CSS_SELECTOR,".styles_promoItem__aolWq>a[href='/special_offers/promo.html']")
    MAIN_CAT_OFFERS = (By.XPATH, "(//*[@href='/special_offers/promo.html?discountTypes=sale'])[1]")
    MAIN_CAT_TIRES = (By.XPATH, "(//*[@href='/tires/'])[1]")
    MAIN_CAT_REFREG = (By.XPATH, "//*[@href='/refrigerators/']")
    MAIN_CAT_MOBILE = (By.XPATH, "//*[@href='/mobile/']")
    MAIN_CAT_NOTEBOOK = (By.XPATH, "//*[@href='/notebooks/']")
    MAIN_CAT_TV = (By.XPATH, "(//*[@class='styles_promoItem__aolWq'])[7]")
    MAIN_CAT_VACUUM = (By.XPATH, "(//*[@class='styles_promoItem__aolWq'])[8]")
    MAIN_CAT_MATRAS = (By.XPATH, "//*[@href='/mattresses/']")
    MAIN_CAT_SOFAS = (By.XPATH, "//*[@href='/cushioned_furniture/']")
    MAIN_CAT_KITCHEN = (By.XPATH, "//*[@href='/kitchen_furniture/']")
    MAIN_CAT_BATTERIES = (By.XPATH, "//*[@href='/car_batteries/']")
    MAIN_GOODS_WITH_GIFTS = (By.XPATH, "//*[text()='Товары с подарками']")
    MAIN_ICON_GIFTS = (By.XPATH, '//*[text()="+ Подарок"]')
    MAIN_XIAOMI = (By.XPATH, "//*[@data-id='33874']")
    MAIN_SEE_ALL_OFFERS = (By.XPATH,"//*[@class='SpecialOffersList_link__fOWwb']")
    MAIN_POPULAR_100 = (By.XPATH, "(//*[@class='Chip_label__oZTDw ChipHome_label__pG1wI'])[7]")
    MAIN_POPULAR_COST = (By.XPATH,"(//*[@data-testid='card-current-price' and text()='85,80 р.'])")
    MAIN_COOKIE_OVERLAY = (By.XPATH, "//*[@id='modal-cookie']/div")
    MAIN_COOKIE_ACCEPT = (By.XPATH, "//*[text()='Принять']")
    MAIN_TO_BASKET = (By.XPATH, "(//*[@class='ProductHome_actions___ekjB'])[1]")
    MAIN_FUTER_TS = (By.CSS_SELECTOR, "[href='/company/trucking.html']")
    MAIN_GOODS_IN_BASKET = (By.XPATH, "//*[@data-testid='header-count']")
    MAIN_INSTAGRAM = (By.XPATH, "//*[@class='styles_instagram__qMBNA styles_icon__MJQpT']")
    MAIN_USER = (By.XPATH, "//*[@class='styles_userToolsToggler__c2aHe']")
    MAIN_USER_ICON = (By.XPATH, "//*[@class='styles_userToolsIcon__Y2sGs']")
    MAIN_DropDown = (By.XPATH, "//*[@data-testid='loginButton']")
    SING_IN_FILED = (By.XPATH, "//input[@id='login-email']")
    SING_IN_PASSWORD = (By.XPATH, "//*[@name='password']")
    SING_IN_ENTER = (By.XPATH, "//*[@data-testid='loginSubmit']")
    SING_IN_ERROR = (By.XPATH, '//*[@class="styles_errorText__LEN7M"]')
    OFFERS_FILTER_PRICE_UP_TO = (By.XPATH, "(//*[@class='NewInput_inputStyle__2uziF'])[2]")
    OFFERS_FILTER50_COST = (By.XPATH, "(//*[@class='style_currentPrice__Lp9e2' and text()='25,90 р.'])[1]")
